export const paymentStatusStates = {
  showPaymentInputs: true,
  showCreditCard: false,
  showPaypal: false,
  showPaymentSelection: true,
  showPaymentInfo: false,
  showPayment: true,
  showSelectPayment: true,
};

export const solutionistWorkSettingsStates = {
  id: 0,
  businessStartTime: "",
  businessEndTime: "",
  oneBlockedStatus: false,
  jobASAPStatus: false,
  onlineStatus: false,
  availableDays: "",
  vacationStatus: false,
  vacationStartDate: "",
  vacationEndDate: "",
  twentyFourHoursStatus: false,
  twelveHoursStatus: false,
};

export const customerDetails = {
  id: -1,
  name: "",
  email: "",
  password: "",
  role: "",
  username: "",
  passwordHash: "",
  phoneNumber: "",
  profilePicture: "",
  dateOfBirth: "",
  location: "",
  createdAt: "",
  updatedAt: "",
  termsAccepted: false,
  privacyPolicyAccepted: false,
  middleName: "",
  lastName: "",
  firstName: "",
  fullName: "",
  isVerified: false,
  verificationToken: "",
  resetPasswordToken: "",
  resetPasswordExpiration: "",
  lastLogin: "",
  loginAttempts: 0,
  isLocked: false,
  notificationPreferences: "",
  preferredTheme: "",
  gender: "",
  nationality: "",
  permissions: "",
  roleLevel: 0,
  lastLoginIp: "",
  deviceInfo: "",
  subscriptionType: "",
  subscriptionStatus: "",
  subscriptionStartDate: "",
  subscriptionEndDate: "",
  referralCode: "",
  referredBy: "",
  isDeleted: false,
  deletedAt: "",
};

export const customerAddressDetails = {
  id: -1,
  userId: -1,
  street: "",
  addressLine2: null,
  city: "",
  state: "",
  region: "",
  postalCode: "",
  country: "",
  latitude: 0,
  longitude: 0,
  addressType: "",
  label: "",
  isDefault: false,
  isVerified: false,
  permanent: false,
  createdAt: "",
  updatedAt: "",
};

export const orderStates = {
  orderID: -1,
  customerInfo: customerDetails,
  customerAddress: customerAddressDetails,
  solutionDateContract: {
    solutionDate: "",
    longTermContract: "",
    longTermstartDate: "",
    longTermEndDate: "",
    solutionFormattedDate: "",
    solutionStartTime: "",
  },
  paymentInfo: {
    nameOnCard: "",
    cardNumber: "",
    cardType: "",
    expirationDate: "",
    securityCode: "",
    postalCode: "",
  },
  solutionTask: "",
  solutionJob: "",
  selectedTalent: "",
  talentID: 0,
  talentFirstName: "",
  talentLastName: "",
  solutionPrice: 0,
  fixPriceStatus: false,
  solutionPriceDiscountPercentage: 0,
  orderDate: "",
  orderStatus: false,
  giftStatus: false,
  giftInformationFor: {
    firstName: "",
    lastName: "",
    country: "",
    street: "",
    city: "",
    state: "",
    postalCode: "",
    phoneNumber: "",
    email: "",
  },
  longTermSubscriptionAllow: false,
};

export const postAJobFormDetails = {
  id: "",
  jobName: "",
  jobTask: "",
  jobPrice: "",
  jobZip: "",
  jobCityLocation: "",
  jobDate: "",
  time: "",
  email: "",
  jobCountry: "",
  jobState: "",
  urgencyLevel: "",
  phoneNumber: "",
  customerName: "",
  jobAddress: "",
};
