export const paymentStatusStates = {
  showPaymentInputs: true,
  showCreditCard: false,
  showPaypal: false,
  showPaymentSelection: true,
  showPaymentInfo: false,
  showPayment: true,
  showSelectPayment: true,
};

export const customerOrderStatess = {
  orderID: 0,
  customerID: 0,
  firstName: "",
  lastName: "",
  country: "",
  address: "",
  city: "",
  state: "",
  zip: "",
  phoneNumber: "",
  email: "",
  solutionFormattedDate: "",
  solutionDate: "",
  solutionTask: "",
  solutionJob: "",
  solutionStartTime: "",
  selectedTalent: "",
  talentID: 0,
  talentFirstName: "",
  talentLastName: "",
  solutionPrice: 0,
  solutionPricePerHourStatus: false,
  solutionPriceDiscountPercentage: 0,
  orderDate: "",
  orderStatus: false,
  giftStatus: false,
  giftFor_fullName: "",
};

export const orderStates = {
  orderID: 0,
  customerID: 0,
  firstName: "",
  lastName: "",
  country: "",
  address: "",
  city: "",
  state: "",
  zip: "",
  phoneNumber: "",
  solutionFormattedDate: "",
  solutionDate: "",
  solutionTask: "",
  solutionJob: "",
  solutionStartTime: "",
  selectedTalent: "",
  talentID: 0,
  talentFirstName: "",
  talentLastName: "",
  solutionPrice: 0,
  solutionPricePerHourStatus: false,
  solutionPriceDiscountPercentage: 0,
  orderDate: "",
  orderStatus: false,
};
